-- Migration: Create reg_personajes_entrenamientos table and migrate existing data
-- Description: Establishes N:M relationship for character trainings and migrates single slot trainings from reg_personajes_ramas.

-- 1. Create table reg_personajes_entrenamientos
CREATE TABLE IF NOT EXISTS public.reg_personajes_entrenamientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_id BIGINT NOT NULL REFERENCES public.reg_characters(id) ON DELETE CASCADE,
    rama_id BIGINT NOT NULL REFERENCES public.info_ramas_clanes(id) ON DELETE CASCADE,
    entrenamiento_id BIGINT NOT NULL REFERENCES public.info_entrenamientos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_personaje_entrenamiento UNIQUE (personaje_id, entrenamiento_id)
);

-- 2. Migrate existing single training allocations to new table
INSERT INTO public.reg_personajes_entrenamientos (personaje_id, rama_id, entrenamiento_id)
SELECT personaje_id, rama_id, id_entrenamiento
FROM public.reg_personajes_ramas
WHERE id_entrenamiento IS NOT NULL
ON CONFLICT DO NOTHING;

-- 3. Drop id_entrenamiento column from reg_personajes_ramas to prevent duplicate sources of truth
ALTER TABLE public.reg_personajes_ramas DROP COLUMN IF EXISTS id_entrenamiento;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.reg_personajes_entrenamientos ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies
CREATE POLICY "Lectura pública de entrenamientos personajes" 
ON public.reg_personajes_entrenamientos FOR SELECT 
USING (true);

CREATE POLICY "Usuarios pueden gestionar sus propios entrenamientos" 
ON public.reg_personajes_entrenamientos FOR ALL 
TO authenticated 
USING (personaje_id IN (SELECT id FROM public.reg_characters WHERE user_id = auth.uid()));

CREATE POLICY "Admins pueden gestionar todos los entrenamientos" 
ON public.reg_personajes_entrenamientos FOR ALL 
TO authenticated 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- 6. Create optimized btree indexes for search filters
CREATE INDEX IF NOT EXISTS idx_reg_personajes_entrenamientos_personaje_id 
ON public.reg_personajes_entrenamientos USING btree (personaje_id);

CREATE INDEX IF NOT EXISTS idx_reg_personajes_entrenamientos_rama_id 
ON public.reg_personajes_entrenamientos USING btree (rama_id);

CREATE INDEX IF NOT EXISTS idx_reg_personajes_entrenamientos_entrenamiento_id 
ON public.reg_personajes_entrenamientos USING btree (entrenamiento_id);
