-- Migration: Add rasgos system
-- Description: Create info_rasgos, reg_personajes_rasgos, and update info_ramas_clanes for traits.

-- 1. Create table info_rasgos
CREATE TABLE IF NOT EXISTS public.info_rasgos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL CHECK (categoria IN ('Físico', 'Psicológico', 'Habilidad')),
    rango TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    especial BOOLEAN NOT NULL DEFAULT false,
    personajes JSONB NOT NULL DEFAULT '[]'::jsonb,
    stat TEXT NULL CHECK (stat IN ('NIN', 'GEN', 'TAI', 'SM', 'FUE', 'AGI', 'EST', 'INT')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create junction table reg_personajes_rasgos
CREATE TABLE IF NOT EXISTS public.reg_personajes_rasgos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_id BIGINT NOT NULL REFERENCES public.reg_characters(id) ON DELETE CASCADE,
    rasgo_id BIGINT NOT NULL REFERENCES public.info_rasgos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_personaje_rasgo UNIQUE (personaje_id, rasgo_id)
);

-- 3. Add rasgo_id to info_ramas_clanes
ALTER TABLE public.info_ramas_clanes 
ADD COLUMN IF NOT EXISTS rasgo_id BIGINT REFERENCES public.info_rasgos(id) ON DELETE SET NULL;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.info_rasgos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_personajes_rasgos ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies for info_rasgos
CREATE POLICY "Lectura pública de rasgos" 
ON public.info_rasgos FOR SELECT 
USING (true);

CREATE POLICY "Admins pueden gestionar todos los rasgos" 
ON public.info_rasgos FOR ALL 
TO authenticated
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- 6. Create RLS Policies for reg_personajes_rasgos
CREATE POLICY "Lectura pública de rasgos personajes" 
ON public.reg_personajes_rasgos FOR SELECT 
USING (true);

CREATE POLICY "Usuarios pueden gestionar sus propios rasgos" 
ON public.reg_personajes_rasgos FOR ALL 
TO authenticated
USING (personaje_id IN (SELECT id FROM public.reg_characters WHERE user_id = auth.uid()));

CREATE POLICY "Admins pueden gestionar todos los rasgos personajes" 
ON public.reg_personajes_rasgos FOR ALL 
TO authenticated
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- 7. Create indexes for optimization
CREATE INDEX IF NOT EXISTS idx_reg_personajes_rasgos_personaje_id ON public.reg_personajes_rasgos(personaje_id);
CREATE INDEX IF NOT EXISTS idx_reg_personajes_rasgos_rasgo_id ON public.reg_personajes_rasgos(rasgo_id);
CREATE INDEX IF NOT EXISTS idx_info_ramas_clanes_rasgo_id ON public.info_ramas_clanes(rasgo_id);
