-- Migration: Create reg_equipos_ninja table, triggers and RLS policies
-- Description: Sets up the teams table, RLS, indexes and dynamic constraints check.

-- 1. Create table reg_equipos_ninja
CREATE TABLE IF NOT EXISTS public.reg_equipos_ninja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_equipo TEXT NOT NULL,
    aldea_id BIGINT NOT NULL REFERENCES public.info_aldeas(id) ON DELETE CASCADE,
    lider_id BIGINT NOT NULL REFERENCES public.reg_characters(id) ON DELETE CASCADE,
    integrante_1_id BIGINT REFERENCES public.reg_characters(id) ON DELETE SET NULL,
    integrante_2_id BIGINT REFERENCES public.reg_characters(id) ON DELETE SET NULL,
    integrante_3_id BIGINT REFERENCES public.reg_characters(id) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_disolucion TIMESTAMPTZ,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Create optimized btree indexes
CREATE INDEX IF NOT EXISTS idx_reg_equipos_ninja_aldea_id 
ON public.reg_equipos_ninja USING btree (aldea_id);

CREATE INDEX IF NOT EXISTS idx_reg_equipos_ninja_lider_id_active 
ON public.reg_equipos_ninja (lider_id) WHERE (activo = true);

CREATE INDEX IF NOT EXISTS idx_reg_equipos_ninja_int1_id_active 
ON public.reg_equipos_ninja (integrante_1_id) WHERE (activo = true);

CREATE INDEX IF NOT EXISTS idx_reg_equipos_ninja_int2_id_active 
ON public.reg_equipos_ninja (integrante_2_id) WHERE (activo = true);

CREATE INDEX IF NOT EXISTS idx_reg_equipos_ninja_int3_id_active 
ON public.reg_equipos_ninja (integrante_3_id) WHERE (activo = true);

-- 3. Validation and transition trigger function
CREATE OR REPLACE FUNCTION public.fn_validar_reg_equipos_ninja()
RETURNS TRIGGER AS $$
DECLARE
    v_lider_aldea bigint;
    v_int1_aldea bigint;
    v_int2_aldea bigint;
    v_int3_aldea bigint;
    v_lider_rango text;
    v_player_count integer;
    v_prev_team record;
    v_char_id bigint;
    v_char_name text;
    v_char_ids bigint[];
BEGIN
    -- Si se desactiva el equipo, no hacemos validaciones de integridad de miembros
    IF NEW.activo = false THEN
        IF NEW.fecha_disolucion IS NULL THEN
            NEW.fecha_disolucion := now();
        END IF;
        RETURN NEW;
    END IF;

    -- 1. Validar cantidad de miembros (mínimo 2, máximo 4)
    v_player_count := 0;
    IF NEW.lider_id IS NOT NULL THEN v_player_count := v_player_count + 1; END IF;
    IF NEW.integrante_1_id IS NOT NULL THEN v_player_count := v_player_count + 1; END IF;
    IF NEW.integrante_2_id IS NOT NULL THEN v_player_count := v_player_count + 1; END IF;
    IF NEW.integrante_3_id IS NOT NULL THEN v_player_count := v_player_count + 1; END IF;

    IF v_player_count < 2 THEN
        -- Si cae por debajo del mínimo, se desactiva
        NEW.activo := false;
        NEW.fecha_disolucion := now();
        RETURN NEW;
    END IF;

    -- 2. Asegurar que no haya duplicados entre los IDs de los miembros
    IF (NEW.lider_id = NEW.integrante_1_id) OR 
       (NEW.integrante_2_id IS NOT NULL AND (NEW.lider_id = NEW.integrante_2_id OR NEW.integrante_1_id = NEW.integrante_2_id)) OR
       (NEW.integrante_3_id IS NOT NULL AND (NEW.lider_id = NEW.integrante_3_id OR NEW.integrante_1_id = NEW.integrante_3_id OR NEW.integrante_2_id = NEW.integrante_3_id)) THEN
        RAISE EXCEPTION 'Un personaje no puede ocupar múltiples puestos en el mismo equipo.';
    END IF;

    -- 3. Validar aldeas y rango jerárquico del líder
    SELECT aldea_id, rango_jerarquico, nombre_ninja INTO v_lider_aldea, v_lider_rango, v_char_name
    FROM public.reg_characters
    WHERE id = NEW.lider_id;

    IF LOWER(COALESCE(v_lider_rango, '')) = 'genin' THEN
        RAISE EXCEPTION 'El líder del equipo (%) debe ser rango Chunin o superior y no Genin.', v_char_name;
    END IF;

    IF v_lider_aldea IS DISTINCT FROM NEW.aldea_id THEN
        RAISE EXCEPTION 'El líder del equipo (%) no pertenece a la aldea seleccionada.', v_char_name;
    END IF;

    -- Validar integrante 1
    IF NEW.integrante_1_id IS NOT NULL THEN
        SELECT aldea_id INTO v_int1_aldea FROM public.reg_characters WHERE id = NEW.integrante_1_id;
        IF v_int1_aldea IS DISTINCT FROM NEW.aldea_id THEN
            RAISE EXCEPTION 'El integrante 1 no pertenece a la misma aldea que el equipo.';
        END IF;
    END IF;

    -- Validar integrante 2
    IF NEW.integrante_2_id IS NOT NULL THEN
        SELECT aldea_id INTO v_int2_aldea FROM public.reg_characters WHERE id = NEW.integrante_2_id;
        IF v_int2_aldea IS DISTINCT FROM NEW.aldea_id THEN
            RAISE EXCEPTION 'El integrante 2 no pertenece a la misma aldea que el equipo.';
        END IF;
    END IF;

    -- Validar integrante 3
    IF NEW.integrante_3_id IS NOT NULL THEN
        SELECT aldea_id INTO v_int3_aldea FROM public.reg_characters WHERE id = NEW.integrante_3_id;
        IF v_int3_aldea IS DISTINCT FROM NEW.aldea_id THEN
            RAISE EXCEPTION 'El integrante 3 no pertenece a la misma aldea que el equipo.';
        END IF;
    END IF;

    -- 4. Procesar transiciones de equipo para cada uno de los personajes
    v_char_ids := ARRAY[]::bigint[];
    IF NEW.lider_id IS NOT NULL THEN v_char_ids := array_append(v_char_ids, NEW.lider_id); END IF;
    IF NEW.integrante_1_id IS NOT NULL THEN v_char_ids := array_append(v_char_ids, NEW.integrante_1_id); END IF;
    IF NEW.integrante_2_id IS NOT NULL THEN v_char_ids := array_append(v_char_ids, NEW.integrante_2_id); END IF;
    IF NEW.integrante_3_id IS NOT NULL THEN v_char_ids := array_append(v_char_ids, NEW.integrante_3_id); END IF;

    FOREACH v_char_id IN ARRAY v_char_ids LOOP
        -- Buscar si está en otro equipo activo
        SELECT * INTO v_prev_team
        FROM public.reg_equipos_ninja
        WHERE activo = true
          AND id IS DISTINCT FROM NEW.id
          AND (lider_id = v_char_id OR integrante_1_id = v_char_id OR integrante_2_id = v_char_id OR integrante_3_id = v_char_id)
        LIMIT 1;

        IF v_prev_team.id IS NOT NULL THEN
            -- Validar si han pasado las 2 semanas
            IF now() < v_prev_team.fecha_creacion + INTERVAL '14 days' THEN
                SELECT nombre_ninja INTO v_char_name FROM public.reg_characters WHERE id = v_char_id;
                RAISE EXCEPTION 'El personaje % no puede cambiar de equipo hasta transcurridas 2 semanas desde la creación de su equipo actual (%)', v_char_name, v_prev_team.nombre_equipo;
            END IF;

            -- Si ya pasaron las 2 semanas, lo removemos de ese equipo
            IF v_prev_team.lider_id = v_char_id THEN
                UPDATE public.reg_equipos_ninja
                SET activo = false, fecha_disolucion = now()
                WHERE id = v_prev_team.id;
            ELSIF v_prev_team.integrante_1_id = v_char_id THEN
                UPDATE public.reg_equipos_ninja
                SET integrante_1_id = NULL
                WHERE id = v_prev_team.id;
            ELSIF v_prev_team.integrante_2_id = v_char_id THEN
                UPDATE public.reg_equipos_ninja
                SET integrante_2_id = NULL
                WHERE id = v_prev_team.id;
            ELSIF v_prev_team.integrante_3_id = v_char_id THEN
                UPDATE public.reg_equipos_ninja
                SET integrante_3_id = NULL
                WHERE id = v_prev_team.id;
            END IF;
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Create trigger
DROP TRIGGER IF EXISTS tr_validar_reg_equipos_ninja ON public.reg_equipos_ninja;
CREATE TRIGGER tr_validar_reg_equipos_ninja
BEFORE INSERT OR UPDATE ON public.reg_equipos_ninja
FOR EACH ROW
EXECUTE FUNCTION public.fn_validar_reg_equipos_ninja();

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.reg_equipos_ninja ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS Policies
CREATE POLICY "Lectura pública de equipos" 
ON public.reg_equipos_ninja FOR SELECT 
USING (true);

CREATE POLICY "Usuarios autenticados pueden crear equipos" 
ON public.reg_equipos_ninja FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Miembros del equipo y admins pueden modificar/disolver" 
ON public.reg_equipos_ninja FOR UPDATE 
TO authenticated 
USING (
    lider_id IN (SELECT id FROM public.reg_characters WHERE user_id = auth.uid()) OR
    integrante_1_id IN (SELECT id FROM public.reg_characters WHERE user_id = auth.uid()) OR
    integrante_2_id IN (SELECT id FROM public.reg_characters WHERE user_id = auth.uid()) OR
    integrante_3_id IN (SELECT id FROM public.reg_characters WHERE user_id = auth.uid()) OR
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
)
WITH CHECK (true);
