-- Crear tabla info_npc para gestionar NPCs por aldea y renegados
CREATE TABLE IF NOT EXISTS public.info_npc (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aldea_id BIGINT REFERENCES public.info_aldeas(id) ON DELETE SET NULL,
  img_url TEXT,
  title TEXT,
  name TEXT NOT NULL,
  age TEXT,
  clan TEXT,
  ability TEXT,
  history TEXT,
  psychic TEXT,
  psicologic TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.info_npc ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública
CREATE POLICY "Permitir lectura pública de info_npc"
  ON public.info_npc
  FOR SELECT
  USING (true);

-- Índices de optimización
CREATE INDEX IF NOT EXISTS idx_info_npc_aldea_id ON public.info_npc(aldea_id);
