-- Migration: Create info_acompanantes and reg_personajes_acompanantes tables
-- Description: Establishes catalog for companion types and registration for character companion instances.

-- 1. Create table info_acompanantes
CREATE TABLE IF NOT EXISTS public.info_acompanantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rama_clan_id BIGINT NOT NULL REFERENCES public.info_ramas_clanes(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    url_default TEXT NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create table reg_personajes_acompanantes
CREATE TABLE IF NOT EXISTS public.reg_personajes_acompanantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_id BIGINT NOT NULL REFERENCES public.reg_characters(id) ON DELETE CASCADE,
    acompanante_id BIGINT NOT NULL REFERENCES public.info_acompanantes(id) ON DELETE CASCADE,
    nombre_personalizado TEXT,
    url_image_personalizada TEXT,
    origen TEXT NOT NULL, -- 'base', 'entrenamiento_mure', 'entrenamiento_ekibyo_tsukai', etc.
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_personaje_origen UNIQUE (personaje_id, origen)
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.info_acompanantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_personajes_acompanantes ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for info_acompanantes
CREATE POLICY "Lectura pública de info_acompanantes" 
ON public.info_acompanantes FOR SELECT 
USING (true);

CREATE POLICY "Admins pueden gestionar info_acompanantes" 
ON public.info_acompanantes FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() 
        AND profiles.role = 'admin'
    )
);

-- 5. Create RLS Policies for reg_personajes_acompanantes
CREATE POLICY "Lectura pública de reg_personajes_acompanantes" 
ON public.reg_personajes_acompanantes FOR SELECT 
USING (true);

CREATE POLICY "Usuarios pueden gestionar sus propios acompañantes" 
ON public.reg_personajes_acompanantes FOR ALL 
TO authenticated 
USING (
    personaje_id IN (
        SELECT id FROM public.reg_characters 
        WHERE user_id = auth.uid()
    )
)
WITH CHECK (
    personaje_id IN (
        SELECT id FROM public.reg_characters 
        WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Admins pueden gestionar todos los acompañantes" 
ON public.reg_personajes_acompanantes FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() 
        AND profiles.role = 'admin'
    )
);

-- 6. Create Indexes
CREATE INDEX IF NOT EXISTS idx_info_acompanantes_rama_clan_id ON public.info_acompanantes USING btree (rama_clan_id);
CREATE INDEX IF NOT EXISTS idx_reg_personajes_acompanantes_personaje_id ON public.reg_personajes_acompanantes USING btree (personaje_id);
CREATE INDEX IF NOT EXISTS idx_reg_personajes_acompanantes_acompanante_id ON public.reg_personajes_acompanantes USING btree (acompanante_id);
