-- Migración: Crear tabla para el Clan Uchiha (Rama de Combate, Tomoes y Rama Copia Hasei: Kopī)
-- Ruta: supabase/migrations/20260902120000_create_uchiha_tables.sql

CREATE TABLE IF NOT EXISTS public.reg_personajes_uchiha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_id BIGINT UNIQUE NOT NULL REFERENCES public.reg_characters(id) ON DELETE CASCADE,
    rama_combate TEXT CHECK (rama_combate IN ('Ninjutsu', 'Taijutsu', 'Genjutsu', 'Shurikenjutsu', 'Bujutsu')),
    slots_desbloqueados JSONB DEFAULT '["D_1", "D_2"]'::jsonb NOT NULL,
    copias JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Índices de rendimiento
CREATE INDEX IF NOT EXISTS idx_reg_personajes_uchiha_personaje_id 
    ON public.reg_personajes_uchiha(personaje_id);

-- Habilitar RLS
ALTER TABLE public.reg_personajes_uchiha ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS
CREATE POLICY "Lectura pública de reg_personajes_uchiha"
    ON public.reg_personajes_uchiha FOR SELECT
    USING (true);

CREATE POLICY "Usuarios pueden gestionar sus propios datos uchiha"
    ON public.reg_personajes_uchiha FOR ALL
    TO authenticated
    USING (
        personaje_id IN (
            SELECT reg_characters.id 
            FROM public.reg_characters 
            WHERE reg_characters.user_id = auth.uid()
        )
    )
    WITH CHECK (
        personaje_id IN (
            SELECT reg_characters.id 
            FROM public.reg_characters 
            WHERE reg_characters.user_id = auth.uid()
        )
    );

CREATE POLICY "Admins pueden gestionar todos los datos uchiha"
    ON public.reg_personajes_uchiha FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.role = 'moderador')
        )
    );
