-- Migración: Crear tablas para Kugutsu Kobo (Taller de Marionetas)
-- Ruta: supabase/migrations/20260701161500_create_kugutsu_tables.sql

-- 1. Crear tabla de componentes de marioneta
CREATE TABLE IF NOT EXISTS public.info_kugutsu_componentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_esp TEXT NOT NULL,
    nombre_jap TEXT NOT NULL,
    url_image TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('cuerpo', 'extremidad', 'accesorio')),
    activo BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Crear tabla intermedia de ensamblado de marionetas
CREATE TABLE IF NOT EXISTS public.reg_personajes_kugutsu_componentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_acompanante_id BIGINT UNIQUE NOT NULL REFERENCES public.reg_personajes_acompanantes(id) ON DELETE CASCADE,
    personaje_id BIGINT NOT NULL REFERENCES public.reg_characters(id) ON DELETE CASCADE,
    cuerpo_id BIGINT REFERENCES public.info_kugutsu_componentes(id) ON DELETE SET NULL,
    extremidad_id BIGINT REFERENCES public.info_kugutsu_componentes(id) ON DELETE SET NULL,
    accesorio_id BIGINT REFERENCES public.info_kugutsu_componentes(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Crear índices de rendimiento
CREATE INDEX IF NOT EXISTS idx_reg_personajes_kugutsu_componentes_personaje_id 
    ON public.reg_personajes_kugutsu_componentes(personaje_id);
CREATE INDEX IF NOT EXISTS idx_reg_personajes_kugutsu_componentes_acompanante_id 
    ON public.reg_personajes_kugutsu_componentes(personaje_acompanante_id);

-- 4. Habilitar RLS en las nuevas tablas
ALTER TABLE public.info_kugutsu_componentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reg_personajes_kugutsu_componentes ENABLE ROW LEVEL SECURITY;

-- 5. Crear políticas para info_kugutsu_componentes
CREATE POLICY "Lectura pública de info_kugutsu_componentes"
    ON public.info_kugutsu_componentes FOR SELECT
    USING (true);

CREATE POLICY "Admins pueden gestionar todos los componentes de marioneta"
    ON public.info_kugutsu_componentes FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );

-- 6. Crear políticas para reg_personajes_kugutsu_componentes
CREATE POLICY "Lectura pública de reg_personajes_kugutsu_componentes"
    ON public.reg_personajes_kugutsu_componentes FOR SELECT
    USING (true);

CREATE POLICY "Usuarios pueden gestionar sus propios componentes de marioneta"
    ON public.reg_personajes_kugutsu_componentes FOR ALL
    TO authenticated
    USING (
        personaje_id IN (
            SELECT reg_characters.id 
            FROM public.reg_characters 
            WHERE reg_characters.user_id = auth.uid()
        )
    )
    WITH CHECK (
        personaje_id IN (
            SELECT reg_characters.id 
            FROM public.reg_characters 
            WHERE reg_characters.user_id = auth.uid()
        )
    );

CREATE POLICY "Admins pueden gestionar todos los ensamblados de marioneta"
    ON public.reg_personajes_kugutsu_componentes FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );

-- 7. Insertar la plantilla de marioneta base en info_acompanantes si no existe
INSERT INTO public.info_acompanantes (rama_clan_id, nombre_esp, nombre_jap, slug, url_default, activo)
SELECT 28, 'Marioneta', 'Kugutsu', 'kugutsu', NULL, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM public.info_acompanantes WHERE slug = 'kugutsu'
);
